name: Docker

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Pull the Docker images
        run: |
          docker compose pull web

      - name: Build the Docker images
        run: |
          docker compose build py-sc-server nika-ui problem-solver

      - name: Run Docker Compose
        run: |
          docker compose up -d --wait
