repos:
   - repo: https://github.com/pycqa/isort
     rev: 5.10.1
     hooks:
        - id: isort
          name: isort
          args: [--line-length=120]

   - repo: https://github.com/ambv/black
     rev: 21.10b0
     hooks:
        - id: black
          name: black
          args: [--line-length=120]

   - repo: https://github.com/pycqa/pylint
     rev: v2.11.1
     hooks:
        - id: pylint

